name: Deploy specific files to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Crear un directorio para los archivos de despliegue
      - name: Prepare deployment directory
        run: mkdir deployment

      # Copiar los archivos específicos al directorio de despliegue
      - name: Copy specific files
        run: |
          cp iisstart.htm deployment/
          cp iisstart.png deployment/
          cp web.config deployment/

      # Verificar que los archivos se copiaron correctamente
      - name: Verify files copied
        run: ls -la deployment

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Desplegar a Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myWebAppUsing-NET-GitHub'
          slot-name: 'Production'
          package: deployment/
