name: Deploy specific files to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Crear un directorio para los archivos de despliegue
      - name: Prepare deployment directory
        run: mkdir deployment

      # Copiar los archivos específicos al directorio de despliegue
      - name: Copy specific files
        run: |
          cp iisstart.htm deployment/
          cp iisstart.png deployment/
          cp web.config deployment/

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9441D37EBD834C06A65FFDE34BE9F105 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3844120F37EC48F8832B7FBEF27C2498 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_97146B034E8C41E8893B49B47B723B87 }}

      # Desplegar a Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myWebAppUsing-NET-GitHub'
          slot-name: 'Production'
          package: deployment/
