name: Deploy specific files to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Crear un directorio para los archivos de despliegue
      - name: Prepare deployment directory
        run: mkdir deployment

      # Copiar los archivos específicos al directorio de despliegue
      - name: Copy specific files
        run: |
          cp iisstart.htm deployment/
          cp iisstart.png deployment/
          cp web.config deployment/

      # Desplegar a Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myWebAppUsing-NET-GitHub'
          slot-name: 'Production'
          package: deployment/
