# Simple pipeline to copy specific files to Azure Web App

name: Deploy specific files to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Create deployment directory
        run: mkdir deploy

      - name: Copy specific files
        run: |
          cp iisstart.htm deploy/
          cp iisstart.png deploy/
          # Añade aquí cualquier archivo adicional que desees desplegar
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myWebAppUsing-NET-GitHub'
          slot-name: 'Production'
          package: deploy
